### ISSUE TITLE
New subfilter broke migrated filters

### ISSUE THREAD

**Issue by mwerlen** [thp/urlwatch#547]
Debian packaging of urlwatch includes a simple migration test (between 1.X branch and 2.x branch): very simple `urls.txt` and `hooks.py` files are created and then urlwatch 2.x is launched. We check that urls are migrated into `urls.yaml` and that urlwatch works fine.

`urls.txt` contains this single line:
```
|ls -al ${SOME_EXISTING_AND_NOT_EMPTY_FOLDER}
```

`hooks.py` contains this simple filter :
```python
from urlwatch import html2txt

def filter(url, data):
        if url.startswith(\"http://urlwatch.com/\"):
        return html2txt.html2text(data, method='html2text')
```

Since 2.20, this test fail with this error :
```
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urlwatch/handler.py", line 88, in process
    data = FilterBase.auto_process(self, data)
  File "/usr/lib/python3/dist-packages/urlwatch/filters.py", line 85, in auto_process
    data = filter_instance.filter(data)
TypeError: filter() missing 1 required positional argument: 'subfilter'
---------------------------------------------------------------------------
```

It seems that the new `subfilter` parameter introduced in 2.20 breaks 1.x filters compatibility. 

`LegacyHooksPyFilter` class has a `filter(self, data, subfilter)` function (filters.py:219) but `auto_process` function calls `filter(data)` (filters.py:85), thus triggering the above error.

**Comment by thp** [comment]
This was broken by #522, the commit is 4f76687f.

**Comment by thp** [comment]
Pushed out new release urlwatch 2.21 in case it makes it easier for you to just package the new upstream release with the fix instead of cherry-picking the patch.

**Comment by mwerlen** [comment]
Thanks !
