### ISSUE TITLE
Matrix reporter fails ('NoneType' object has no attribute 'api')

### ISSUE THREAD

**Issue by colorchestra** [thp/urlwatch#516]
I've just tried using the Matrix reporter with urlwatch 2.18. I used to work with 2.16 from the Debian repositories, but uninstalled it and installed 2.18 directly from pip, while keeping my config files in place. I get the following message:

```
urlwatch 2.18, Copyright 2008-2020 Thomas Perl
Website: https://thp.io/2008/urlwatch/
watched 4 URLs in 0 seconds
Traceback (most recent call last):
  File "/home/morph/.local/bin/urlwatch", line 10, in <module>
    sys.exit(main())
  File "/home/morph/.local/lib/python3.7/site-packages/urlwatch/cli.py", line 111, in main
    urlwatch_command.run()
  File "/home/morph/.local/lib/python3.7/site-packages/urlwatch/command.py", line 299, in run
    self.urlwatcher.close()
  File "/home/morph/.local/lib/python3.7/site-packages/urlwatch/main.py", line 99, in close
    self.report.finish()
  File "/home/morph/.local/lib/python3.7/site-packages/urlwatch/handler.py", line 159, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/home/morph/.local/lib/python3.7/site-packages/urlwatch/reporters.py", line 113, in submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "/home/morph/.local/lib/python3.7/site-packages/urlwatch/reporters.py", line 730, in submit
    client_api = matrix_client.api.MatrixHttpApi(homeserver_url, access_token)
AttributeError: 'NoneType' object has no attribute 'api'

```
The same thing happens with both my personal Matrix server and matrix.org.

Is there a way to get more verbose output or another way to debug?

**Comment by thp** [comment]
You need to install the matrix client dependency:

    python3 -m pip install matrix_client
